version: "3"

services:
  grafana:
    image: grafana/grafana:5.1.0
    restart: always
    ports:
      - 3000:3000
    # user: "104"
    #volumes:
    #  - "./grafana-storage:/var/lib/grafana"
    #  - "./plugins:/var/lib/grafana/plugins"
